# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{vzaar}
  s.version = "0.2.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mariusz Lusiak", "Stefano Diem Benatti"]
  s.date = %q{2011-07-19}
  s.description = %q{A gem to be able to use vzaar.com's api with ruby}
  s.email = %q{stefano@tailorbirds.com.br}
  s.extra_rdoc_files = [
    "LICENSE",
    "README"
  ]
  s.files = [
    "Changelog",
    "LICENSE",
    "README",
    "VERSION",
    "demo.rb",
    "lib/rails/controllers/vzaar_controller.rb",
    "lib/rails/views/view_helpers.rb",
    "lib/vzaar.rb",
    "lib/vzaar/account_type.rb",
    "lib/vzaar/base.rb",
    "lib/vzaar/errors.rb",
    "lib/vzaar/signature.rb",
    "lib/vzaar/user.rb",
    "lib/vzaar/video.rb",
    "lib/vzaar/video_details.rb",
    "rails_generators/vzaar_uploader/USAGE",
    "rails_generators/vzaar_uploader/templates/flash/swfupload.swf",
    "rails_generators/vzaar_uploader/templates/flash/swfupload_fp9.swf",
    "rails_generators/vzaar_uploader/templates/images/cancelbutton.gif",
    "rails_generators/vzaar_uploader/templates/javascripts/fileprogress.js",
    "rails_generators/vzaar_uploader/templates/javascripts/handlers.js",
    "rails_generators/vzaar_uploader/templates/javascripts/json_parse.js",
    "rails_generators/vzaar_uploader/templates/javascripts/swfupload.js",
    "rails_generators/vzaar_uploader/templates/javascripts/swfupload.queue.js",
    "rails_generators/vzaar_uploader/templates/stylesheets/swfupload.css",
    "rails_generators/vzaar_uploader/templates/views/uploader.html.erb",
    "rails_generators/vzaar_uploader/vzaar_uploader_generator.rb"
  ]
  s.homepage = %q{http://github.com/tailorbirds/vzaar}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{A gem to be able to use vzaar.com's api with ruby.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<oauth>, ["= 0.3.6"])
      s.add_runtime_dependency(%q<httpclient>, [">= 0"])
    else
      s.add_dependency(%q<oauth>, ["= 0.3.6"])
      s.add_dependency(%q<httpclient>, [">= 0"])
    end
  else
    s.add_dependency(%q<oauth>, ["= 0.3.6"])
    s.add_dependency(%q<httpclient>, [">= 0"])
  end
end

